apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: roadtrip
build:
  local:
    useBuildkit: true
    concurrency: 4
  artifacts:
  - image: roadtrip/map-server
    context: .
    docker:
      dockerfile: docker/mapServer/Dockerfile
  - image: roadtrip/player-server
    context: .
    docker:
      dockerfile: docker/playerServer/Dockerfile
  - image: roadtrip/update-service
    context: .
    docker:
      dockerfile: docker/updateService/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/mapServer/deployment.yaml
    - k8s/playerServer/deployment.yaml
    - k8s/updateService/deployment.yaml
    - k8s/mongodb/deployment.yaml
portForward:
- resourceType: service
  resourceName: playerserver
  port: 9066
- resourceType: service
  resourceName: mongo-service
  port: 27017