apiVersion: v1
kind: Service
metadata:
  name: mapserver
  labels:
    app: mapserver
spec:
  ports:
    - port: 9067
      protocol: TCP
  clusterIP: None
  selector:
    app: mapserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapserver
  labels:
    app: mapserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapserver
  template:
    metadata:
      labels:
        app: mapserver
    spec:
      containers:
      - name: mapserver
        image: 0x01/roadtrip-map-server
