apiVersion: v1
kind: Service
metadata:
  name: updateservice
  labels:
    app: updateservice
spec:
  ports:
  - port: 9068
    protocol: TCP
  clusterIP: None
  selector:
    app: updateservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: updateservice
  labels:
    app: updateservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: updateservice
  template:
    metadata:
      labels:
        app: updateservice
    spec:
      containers:
      - name: updateservice
        image: roadtrip/update-service
