# Use root/example as user/password credentials
version: '3.1'
x-aws-vpc: vpc-0bc7d56fe80cbcd21

services:

  mongo:
    image: mongo
    restart: always
    networks:
      default:
        aliases:
          - playerdb
          - mapdb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  playerServer:
    image: "477748957582.dkr.ecr.us-east-1.amazonaws.com/roadtrip/player-server"
    restart: always
    ports:
      - 9066:9066

  mapServer:
    image: "477748957582.dkr.ecr.us-east-1.amazonaws.com/roadtrip/map-server"
    restart: always

  updateService:
    image: "477748957582.dkr.ecr.us-east-1.amazonaws.com/roadtrip/update-service"
    restart: always
