##
## Run
##
FROM golang:1.16-alpine

WORKDIR /app

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

EXPOSE 9067

ENTRYPOINT ["go", "run", "/app/cmd/mapServer/main.go"]
