// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: internal/mapServer/grpc/map.proto

package map_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{0}
}

type Town struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // format "states/colorado/towns/denver"
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // format "Denver"
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	State       string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // format "states/Colorado"
}

func (x *Town) Reset() {
	*x = Town{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Town) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Town) ProtoMessage() {}

func (x *Town) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Town.ProtoReflect.Descriptor instead.
func (*Town) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{1}
}

func (x *Town) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Town) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Town) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Town) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Road struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // format "roads/i-25"
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	LengthMiles int32  `protobuf:"varint,3,opt,name=length_miles,json=lengthMiles,proto3" json:"length_miles,omitempty"`
	TownA       string `protobuf:"bytes,4,opt,name=town_a,json=townA,proto3" json:"town_a,omitempty"`
	TownB       string `protobuf:"bytes,5,opt,name=town_b,json=townB,proto3" json:"town_b,omitempty"`
}

func (x *Road) Reset() {
	*x = Road{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Road) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Road) ProtoMessage() {}

func (x *Road) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Road.ProtoReflect.Descriptor instead.
func (*Road) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{2}
}

func (x *Road) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Road) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Road) GetLengthMiles() int32 {
	if x != nil {
		return x.LengthMiles
	}
	return 0
}

func (x *Road) GetTownA() string {
	if x != nil {
		return x.TownA
	}
	return ""
}

func (x *Road) GetTownB() string {
	if x != nil {
		return x.TownB
	}
	return ""
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // format "states/colorado"
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{3}
}

func (x *State) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *State) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetTownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTownRequest) Reset() {
	*x = GetTownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTownRequest) ProtoMessage() {}

func (x *GetTownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTownRequest.ProtoReflect.Descriptor instead.
func (*GetTownRequest) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{4}
}

func (x *GetTownRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTownsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ListTownsRequest) Reset() {
	*x = ListTownsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTownsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTownsRequest) ProtoMessage() {}

func (x *ListTownsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTownsRequest.ProtoReflect.Descriptor instead.
func (*ListTownsRequest) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{5}
}

func (x *ListTownsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListTownsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Towns []*Town `protobuf:"bytes,1,rep,name=towns,proto3" json:"towns,omitempty"`
}

func (x *ListTownsResponse) Reset() {
	*x = ListTownsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTownsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTownsResponse) ProtoMessage() {}

func (x *ListTownsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTownsResponse.ProtoReflect.Descriptor instead.
func (*ListTownsResponse) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{6}
}

func (x *ListTownsResponse) GetTowns() []*Town {
	if x != nil {
		return x.Towns
	}
	return nil
}

type ListRoadsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"` // ie "/states/colorado/towns/denver"
}

func (x *ListRoadsRequest) Reset() {
	*x = ListRoadsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoadsRequest) ProtoMessage() {}

func (x *ListRoadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoadsRequest.ProtoReflect.Descriptor instead.
func (*ListRoadsRequest) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{7}
}

func (x *ListRoadsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type ListRoadsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roads []*Road `protobuf:"bytes,1,rep,name=roads,proto3" json:"roads,omitempty"`
}

func (x *ListRoadsResponse) Reset() {
	*x = ListRoadsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoadsResponse) ProtoMessage() {}

func (x *ListRoadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoadsResponse.ProtoReflect.Descriptor instead.
func (*ListRoadsResponse) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{8}
}

func (x *ListRoadsResponse) GetRoads() []*Road {
	if x != nil {
		return x.Roads
	}
	return nil
}

type ListStatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListStatesRequest) Reset() {
	*x = ListStatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatesRequest) ProtoMessage() {}

func (x *ListStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatesRequest.ProtoReflect.Descriptor instead.
func (*ListStatesRequest) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{9}
}

type ListStatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States []*State `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
}

func (x *ListStatesResponse) Reset() {
	*x = ListStatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_mapServer_grpc_map_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatesResponse) ProtoMessage() {}

func (x *ListStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mapServer_grpc_map_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatesResponse.ProtoReflect.Descriptor instead.
func (*ListStatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_mapServer_grpc_map_proto_rawDescGZIP(), []int{10}
}

func (x *ListStatesResponse) GetStates() []*State {
	if x != nil {
		return x.States
	}
	return nil
}

var File_internal_mapServer_grpc_map_proto protoreflect.FileDescriptor

var file_internal_mapServer_grpc_map_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x61, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d, 0x61,
	0x70, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x71, 0x0a, 0x04, 0x54, 0x6f,
	0x77, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x8a, 0x01,
	0x0a, 0x04, 0x52, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x5f, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4d, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06,
	0x74, 0x6f, 0x77, 0x6e, 0x5f, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x77, 0x6e, 0x41, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x77, 0x6e, 0x5f, 0x62, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x6e, 0x42, 0x22, 0x3a, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x77,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x6f, 0x77, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x3d, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x77, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69,
	0x70, 0x5f, 0x6d, 0x61, 0x70, 0x2e, 0x54, 0x6f, 0x77, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x6e,
	0x73, 0x22, 0x2a, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x3d, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x72, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d, 0x61, 0x70,
	0x2e, 0x52, 0x6f, 0x61, 0x64, 0x52, 0x05, 0x72, 0x6f, 0x61, 0x64, 0x73, 0x22, 0x13, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x41, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72,
	0x69, 0x70, 0x5f, 0x6d, 0x61, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x32, 0xbf, 0x02, 0x0a, 0x0b, 0x52, 0x6f, 0x61, 0x64, 0x54, 0x72, 0x69,
	0x70, 0x4d, 0x61, 0x70, 0x12, 0x3d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x77, 0x6e, 0x12,
	0x1c, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d, 0x61, 0x70, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d, 0x61, 0x70, 0x2e, 0x54, 0x6f, 0x77,
	0x6e, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x1f, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d, 0x61, 0x70,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d, 0x61,
	0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f,
	0x77, 0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d,
	0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x77, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d,
	0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x77, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f,
	0x61, 0x64, 0x73, 0x12, 0x1e, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d,
	0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d,
	0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x69, 0x6e, 0x73, 0x6f, 0x66, 0x61,
	0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x6d,
	0x61, 0x70, 0x2f, 0x6d, 0x61, 0x70, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_mapServer_grpc_map_proto_rawDescOnce sync.Once
	file_internal_mapServer_grpc_map_proto_rawDescData = file_internal_mapServer_grpc_map_proto_rawDesc
)

func file_internal_mapServer_grpc_map_proto_rawDescGZIP() []byte {
	file_internal_mapServer_grpc_map_proto_rawDescOnce.Do(func() {
		file_internal_mapServer_grpc_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_mapServer_grpc_map_proto_rawDescData)
	})
	return file_internal_mapServer_grpc_map_proto_rawDescData
}

var file_internal_mapServer_grpc_map_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_mapServer_grpc_map_proto_goTypes = []interface{}{
	(*Empty)(nil),              // 0: roadtrip_map.Empty
	(*Town)(nil),               // 1: roadtrip_map.Town
	(*Road)(nil),               // 2: roadtrip_map.Road
	(*State)(nil),              // 3: roadtrip_map.State
	(*GetTownRequest)(nil),     // 4: roadtrip_map.GetTownRequest
	(*ListTownsRequest)(nil),   // 5: roadtrip_map.ListTownsRequest
	(*ListTownsResponse)(nil),  // 6: roadtrip_map.ListTownsResponse
	(*ListRoadsRequest)(nil),   // 7: roadtrip_map.ListRoadsRequest
	(*ListRoadsResponse)(nil),  // 8: roadtrip_map.ListRoadsResponse
	(*ListStatesRequest)(nil),  // 9: roadtrip_map.ListStatesRequest
	(*ListStatesResponse)(nil), // 10: roadtrip_map.ListStatesResponse
}
var file_internal_mapServer_grpc_map_proto_depIdxs = []int32{
	1,  // 0: roadtrip_map.ListTownsResponse.towns:type_name -> roadtrip_map.Town
	2,  // 1: roadtrip_map.ListRoadsResponse.roads:type_name -> roadtrip_map.Road
	3,  // 2: roadtrip_map.ListStatesResponse.states:type_name -> roadtrip_map.State
	4,  // 3: roadtrip_map.RoadTripMap.GetTown:input_type -> roadtrip_map.GetTownRequest
	9,  // 4: roadtrip_map.RoadTripMap.ListStates:input_type -> roadtrip_map.ListStatesRequest
	5,  // 5: roadtrip_map.RoadTripMap.ListTowns:input_type -> roadtrip_map.ListTownsRequest
	7,  // 6: roadtrip_map.RoadTripMap.ListRoads:input_type -> roadtrip_map.ListRoadsRequest
	1,  // 7: roadtrip_map.RoadTripMap.GetTown:output_type -> roadtrip_map.Town
	10, // 8: roadtrip_map.RoadTripMap.ListStates:output_type -> roadtrip_map.ListStatesResponse
	6,  // 9: roadtrip_map.RoadTripMap.ListTowns:output_type -> roadtrip_map.ListTownsResponse
	8,  // 10: roadtrip_map.RoadTripMap.ListRoads:output_type -> roadtrip_map.ListRoadsResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_mapServer_grpc_map_proto_init() }
func file_internal_mapServer_grpc_map_proto_init() {
	if File_internal_mapServer_grpc_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_mapServer_grpc_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Town); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Road); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTownsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTownsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoadsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoadsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_mapServer_grpc_map_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_mapServer_grpc_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_mapServer_grpc_map_proto_goTypes,
		DependencyIndexes: file_internal_mapServer_grpc_map_proto_depIdxs,
		MessageInfos:      file_internal_mapServer_grpc_map_proto_msgTypes,
	}.Build()
	File_internal_mapServer_grpc_map_proto = out.File
	file_internal_mapServer_grpc_map_proto_rawDesc = nil
	file_internal_mapServer_grpc_map_proto_goTypes = nil
	file_internal_mapServer_grpc_map_proto_depIdxs = nil
}
