// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: internal/grpc/player.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Character) Reset() {
	*x = Character{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_internal_grpc_player_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewCharacterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NewCharacterRequest) Reset() {
	*x = NewCharacterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCharacterRequest) ProtoMessage() {}

func (x *NewCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCharacterRequest.ProtoReflect.Descriptor instead.
func (*NewCharacterRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_player_proto_rawDescGZIP(), []int{1}
}

func (x *NewCharacterRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NewCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_grpc_player_proto_rawDescGZIP(), []int{2}
}

type NameCarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NameCarRequest) Reset() {
	*x = NameCarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameCarRequest) ProtoMessage() {}

func (x *NameCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameCarRequest.ProtoReflect.Descriptor instead.
func (*NameCarRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_player_proto_rawDescGZIP(), []int{3}
}

func (x *NameCarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Plate string `protobuf:"bytes,2,opt,name=plate,proto3" json:"plate,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_internal_grpc_player_proto_rawDescGZIP(), []int{4}
}

func (x *Car) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Car) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *Car) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewCarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NewCarRequest) Reset() {
	*x = NewCarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_player_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCarRequest) ProtoMessage() {}

func (x *NewCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_player_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCarRequest.ProtoReflect.Descriptor instead.
func (*NewCarRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_player_proto_rawDescGZIP(), []int{5}
}

func (x *NewCarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_grpc_player_proto protoreflect.FileDescriptor

var file_internal_grpc_player_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x6f,
	0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x22, 0x33, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x4e,
	0x65, 0x77, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x24, 0x0a, 0x0e, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x03, 0x43, 0x61, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23,
	0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x32, 0xa4, 0x02, 0x0a, 0x0e, 0x52, 0x6f, 0x61, 0x64, 0x54, 0x72, 0x69, 0x70,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69,
	0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72,
	0x69, 0x70, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0x00, 0x12, 0x44,
	0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x1d,
	0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x12, 0x0f,
	0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0d, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x43, 0x61, 0x72, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x12, 0x17, 0x2e, 0x72, 0x6f, 0x61,
	0x64, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x43,
	0x61, 0x72, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x07, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x72, 0x12,
	0x18, 0x2e, 0x72, 0x6f, 0x61, 0x64, 0x74, 0x72, 0x69, 0x70, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x43,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x72, 0x6f, 0x61, 0x64,
	0x74, 0x72, 0x69, 0x70, 0x2e, 0x43, 0x61, 0x72, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x69, 0x6e,
	0x73, 0x6f, 0x66, 0x61, 0x72, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x61, 0x64, 0x54, 0x72,
	0x69, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_player_proto_rawDescOnce sync.Once
	file_internal_grpc_player_proto_rawDescData = file_internal_grpc_player_proto_rawDesc
)

func file_internal_grpc_player_proto_rawDescGZIP() []byte {
	file_internal_grpc_player_proto_rawDescOnce.Do(func() {
		file_internal_grpc_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_player_proto_rawDescData)
	})
	return file_internal_grpc_player_proto_rawDescData
}

var file_internal_grpc_player_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_grpc_player_proto_goTypes = []interface{}{
	(*Character)(nil),           // 0: roadtrip.Character
	(*NewCharacterRequest)(nil), // 1: roadtrip.NewCharacterRequest
	(*Empty)(nil),               // 2: roadtrip.Empty
	(*NameCarRequest)(nil),      // 3: roadtrip.NameCarRequest
	(*Car)(nil),                 // 4: roadtrip.Car
	(*NewCarRequest)(nil),       // 5: roadtrip.NewCarRequest
}
var file_internal_grpc_player_proto_depIdxs = []int32{
	2, // 0: roadtrip.RoadTripPlayer.GetCharacter:input_type -> roadtrip.Empty
	1, // 1: roadtrip.RoadTripPlayer.NewCharacter:input_type -> roadtrip.NewCharacterRequest
	2, // 2: roadtrip.RoadTripPlayer.GetCar:input_type -> roadtrip.Empty
	5, // 3: roadtrip.RoadTripPlayer.NewCar:input_type -> roadtrip.NewCarRequest
	3, // 4: roadtrip.RoadTripPlayer.NameCar:input_type -> roadtrip.NameCarRequest
	0, // 5: roadtrip.RoadTripPlayer.GetCharacter:output_type -> roadtrip.Character
	0, // 6: roadtrip.RoadTripPlayer.NewCharacter:output_type -> roadtrip.Character
	4, // 7: roadtrip.RoadTripPlayer.GetCar:output_type -> roadtrip.Car
	4, // 8: roadtrip.RoadTripPlayer.NewCar:output_type -> roadtrip.Car
	4, // 9: roadtrip.RoadTripPlayer.NameCar:output_type -> roadtrip.Car
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_player_proto_init() }
func file_internal_grpc_player_proto_init() {
	if File_internal_grpc_player_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpc_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Character); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCharacterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameCarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_player_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_player_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_player_proto_goTypes,
		DependencyIndexes: file_internal_grpc_player_proto_depIdxs,
		MessageInfos:      file_internal_grpc_player_proto_msgTypes,
	}.Build()
	File_internal_grpc_player_proto = out.File
	file_internal_grpc_player_proto_rawDesc = nil
	file_internal_grpc_player_proto_goTypes = nil
	file_internal_grpc_player_proto_depIdxs = nil
}
