apiVersion: v1
kind: Service
metadata:
  name: playerserver
  labels:
    app: playerserver
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9066
  selector:
    app: playerserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playerserver
  labels:
    app: playerserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playerserver
  template:
    metadata:
      labels:
        app: playerserver
    spec:
      containers:
        - name: playerserver
          image: 0x01/roadtrip-player-server
          ports:
            - containerPort: 9066
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: roadtrip-ingress
spec:
  ingressClassName: "nginx"
  rules:
    - host: playerserver.roadtrip.insofar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: playerserver
                port:
                  number: 80