apiVersion: v1
kind: Service
metadata:
  name: docker-playerserver
  labels:
    app: docker-playerserver
spec:
  ports:
  - port: 9066
    protocol: TCP
  clusterIP: None
  selector:
    app: docker-playerserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-playerserver
  labels:
    app: docker-playerserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-playerserver
  template:
    metadata:
      labels:
        app: docker-playerserver
    spec:
      containers:
      - name: docker-playerserver
        image: docker-playerserver
